/* GENERATED by build-mock.sh — preview mode only (MOCK:true). */
(function(){
/* Preview mode: runs the real Apps Script backend in the browser on sample data. Built into mock.js. */
var __sheets = {}, __files = {}, __cache = {}, __pushes = [];
var __params = new URLSearchParams(location.search);
var __as = __params.get('as') || 'E-002';
function __fmt(d, tz, f) {
  var p = new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Bangkok', year: 'numeric', month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit', second: '2-digit', hourCycle: 'h23' })
    .formatToParts(d).reduce(function (a, x) { a[x.type] = x.value; return a; }, {});
  if (f === 'H') return String(+p.hour);
  return f.replace('yyyy', p.year).replace('yy', p.year.slice(2)).replace('MM', p.month).replace('dd', p.day).replace('HH', p.hour).replace('mm', p.minute).replace('ss', p.second).replace(/'/g, '');
}
function __sheet(name) {
  var rows = __sheets[name] = __sheets[name] || [];
  return {
    getLastRow: function () { var n = rows.length; while (n > 0 && rows[n - 1].every(function (v) { return v === ''; })) n--; return n; },
    getMaxColumns: function () { return 30; }, getName: function () { return name; },
    getRange: function (r, c, nr, nc) {
      nr = nr || 1; nc = nc || 1;
      return {
        getValues: function () { var o = []; for (var i = 0; i < nr; i++) { var row = []; for (var j = 0; j < nc; j++) { var v = (rows[r - 1 + i] || [])[c - 1 + j]; row.push(v === undefined ? '' : v); } o.push(row); } return o; },
        setValues: function (vals) { vals.forEach(function (row, i) { rows[r - 1 + i] = rows[r - 1 + i] || []; row.forEach(function (v, j) { rows[r - 1 + i][c - 1 + j] = v; }); }); },
        clearContent: function () { }
      };
    }
  };
}
function __bytes(b64) { var s = atob(b64), a = new Array(s.length); for (var i = 0; i < s.length; i++) a[i] = s.charCodeAt(i); return a; }
function __b64(a) { var s = ''; for (var i = 0; i < a.length; i++) s += String.fromCharCode(a[i] & 255); return btoa(s); }
var Utilities = {
  formatDate: __fmt, DigestAlgorithm: { SHA_256: 1 }, Charset: { UTF_8: 1 },
  computeDigest: function (a, v) { var h = 0; for (var i = 0; i < v.length; i++) h = (h * 31 + v.charCodeAt(i)) | 0; var o = []; for (var k = 0; k < 32; k++) o.push((h >> (k % 4 * 8)) & 255); return o; },
  base64Decode: __bytes, base64Encode: __b64,
  newBlob: function (bytes, mime, name) { return { bytes: bytes, mime: mime, name: name }; }
};
var SpreadsheetApp = { getActiveSpreadsheet: function () { return { getSheetByName: function (n) { return __sheets[n] ? __sheet(n) : null; }, getId: function () { return 'mock'; } }; } };
var LockService = { getScriptLock: function () { return { tryLock: function () { return true; }, releaseLock: function () { } }; } };
var CacheService = { getScriptCache: function () { return { get: function (k) { return k in __cache ? __cache[k] : null; }, put: function (k, v) { __cache[k] = v; }, remove: function (k) { delete __cache[k]; } }; } };
var PropertiesService = { getScriptProperties: function () { return { getProperty: function (k) { return { LINE_CHANNEL_ACCESS_TOKEN: 'mock', LIFF_ID: 'mock', LINE_LOGIN_CHANNEL_ID: 'mock' }[k]; } }; } };
var UrlFetchApp = { fetch: function (url, opt) {
  if (url.indexOf('/verify') !== -1) { var sub = String(opt.payload.id_token).replace('mock-', 'U-'); return { getResponseCode: function () { return 200; }, getContentText: function () { return JSON.stringify({ sub: sub, name: 'LINE ' + sub, exp: Date.now() / 1000 + 3600 }); } }; }
  var b = JSON.parse(opt.payload); __pushes.push(b); console.info('[LINE → ' + b.to + ']', b.messages[0].altText);
  return { getResponseCode: function () { return 200; }, getContentText: function () { return '{}'; } };
} };
var DriveApp = {
  getFolderById: function () { return { createFile: function (blob) { var id = 'F' + Object.keys(__files).length; __files[id] = blob; return { getId: function () { return id; } }; } }; },
  getFileById: function (id) { return { getBlob: function () { return { getBytes: function () { return __files[id] ? __files[id].bytes : []; } }; } }; }
};
var ContentService = { MimeType: { JSON: 1 }, createTextOutput: function (s) { return { s: s, setMimeType: function () { return this; } }; } };
var console = window.console;
/**
 * ระบบลา — Config.gs
 * Sheet names, column layouts and seed data. Change rules in the LeaveTypes / Settings
 * tabs after setup, not here (this file is only used to create them the first time).
 */

var TZ = 'Asia/Bangkok';

var SHEETS = {
  EMPLOYEES: 'Employees',
  DEPARTMENTS: 'Departments',
  ADMIN_USERS: 'AdminUsers',
  LEAVE_TYPES: 'LeaveTypes',
  REQUESTS: 'LeaveRequests',
  LEDGER: 'LeaveLedger',
  ATTACHMENTS: 'Attachments',
  HOLIDAYS: 'Holidays',
  SETTINGS: 'Settings',
  NOTIFICATIONS: 'Notifications',
  AUDIT: 'AuditLog'
};

/** Column order of every tab. Row 1 = these headers; data from row 2. */
var SCHEMA = {
  Employees: ['emp_id', 'title', 'first_name', 'last_name', 'nickname', 'dept_id', 'position',
    'hire_date', 'birth_date', 'phone', 'email', 'status', 'resign_date',
    'line_user_id', 'line_linked_at', 'created_at', 'updated_at'],
  Departments: ['dept_id', 'name', 'head_emp_id', 'max_concurrent', 'active'],
  AdminUsers: ['username', 'full_name', 'role', 'emp_id', 'email', 'password_hash', 'salt',
    'must_change_password', 'active', 'failed_logins', 'locked_until', 'line_user_id', 'created_at'],
  LeaveTypes: ['type_id', 'name_th', 'annual_quota', 'max_days_per_request', 'eligible_after_months',
    'notice_days', 'takes_slot', 'blocked_by_slot', 'doc_rule', 'doc_min_days', 'paid_note',
    'filing_window_days', 'color', 'active', 'sort'],
  LeaveRequests: ['req_id', 'emp_id', 'dept_id', 'type_id', 'start_date', 'end_date', 'working_days',
    'reason', 'status', 'approver_emp_id', 'decided_by', 'decided_at', 'decision_note',
    'filed_by', 'leave_year_start', 'created_at', 'updated_at'],
  LeaveLedger: ['entry_id', 'emp_id', 'type_id', 'leave_year_start', 'delta_days', 'kind',
    'req_id', 'by', 'at', 'note'],
  Attachments: ['att_id', 'req_id', 'drive_file_id', 'mime', 'size_kb', 'uploaded_by', 'uploaded_at'],
  Holidays: ['date', 'name_th'],
  Settings: ['key', 'value', 'note'],
  Notifications: ['at', 'to_emp_id', 'template', 'req_id', 'status', 'error'],
  AuditLog: ['at', 'actor', 'role', 'action', 'entity', 'entity_id', 'before_json', 'after_json']
};

/** Columns stored as plain text 'yyyy-MM-dd' (never as Sheets dates, to avoid timezone shifts). */
var DATE_COLS = ['hire_date', 'birth_date', 'resign_date', 'start_date', 'end_date',
  'leave_year_start', 'date'];
/** Columns that must stay text (IDs with leading zeros, phone numbers). */
var TEXT_COLS = ['emp_id', 'dept_id', 'head_emp_id', 'phone', 'username', 'req_id', 'entry_id',
  'att_id', 'approver_emp_id', 'to_emp_id', 'line_user_id', 'type_id', 'key', 'value'];

/**
 * doc_rule: NONE | OPTIONAL | REQUIRED | REQUIRED_IF_MIN_DAYS (uses doc_min_days)
 * annual_quota blank = no yearly balance (as actual / per event / unlimited).
 */
var SEED_LEAVE_TYPES = [
  // type_id, name_th, annual_quota, max_per_req, eligible_after_months, notice, takes_slot, blocked_by_slot, doc_rule, doc_min_days, paid_note, filing_window, color, active, sort
  ['SICK', 'ลาป่วย', 30, '', 0, 0, true, false, 'REQUIRED_IF_MIN_DAYS', 3, 'จ่ายไม่เกิน 30 วัน/ปี', 3, '#E57373', true, 1],
  ['PERS', 'ลากิจ', 3, '', 0, 7, true, true, 'OPTIONAL', '', 'จ่าย', '', '#64B5F6', true, 2],
  ['VAC', 'พักร้อน', 6, '', 12, 7, true, true, 'NONE', '', 'จ่าย', '', '#81C784', true, 3],
  ['ACC', 'ลาอุบัติเหตุจากงาน', '', '', 0, 0, true, false, 'REQUIRED', '', 'ตามกองทุนเงินทดแทน', 3, '#FFB74D', true, 4],
  ['MAT', 'ลาคลอด', '', 120, 0, 7, false, false, 'REQUIRED', '', 'จ่าย 60 วัน', '', '#F06292', true, 5],
  ['SPOUSE', 'ลาช่วยภรรยาคลอด', '', 15, 0, 7, true, true, 'REQUIRED', '', 'จ่าย', '', '#BA68C8', true, 6],
  ['ORD', 'ลาบวช', '', '', 0, 7, false, false, 'OPTIONAL', '', 'ตามนโยบายบริษัท', '', '#FFD54F', true, 7],
  ['MIL', 'ลารับราชการทหาร', '', '', 0, 7, false, false, 'REQUIRED', '', 'จ่ายไม่เกิน 60 วัน/ปี', '', '#90A4AE', true, 8],
  ['TRN', 'ลาฝึกอบรม', '', '', 0, 7, true, true, 'OPTIONAL', '', 'ตามนโยบายบริษัท', '', '#4DB6AC', true, 9],
  ['UNPAID', 'ลาไม่รับค่าจ้าง', '', '', 0, 7, true, true, 'OPTIONAL', '', 'ไม่จ่าย', '', '#A1887F', true, 10]
];

/** Non-secret settings. Secrets (LINE tokens) go in Script Properties, never in the sheet. */
var SEED_SETTINGS = [
  ['work_days', '1,2,3,4,5', 'วันทำงาน 1=จันทร์ … 7=อาทิตย์'],
  ['self_service_after_months', '12', 'พนักงานยื่นลาเองได้หลังทำงานครบกี่เดือน (ก่อนหน้านั้น Super-admin ยื่นแทน)'],
  ['escalation_hours', '24', 'ใบลาค้างกี่ชั่วโมงจึงส่งต่อ Super-admin'],
  ['dept_max_concurrent', '1', 'จำนวนคนลาพร้อมกันได้ต่อแผนกต่อวัน'],
  ['cert_reminder_max', '3', 'เตือนแนบใบรับรองแพทย์สูงสุดกี่ครั้ง'],
  ['attachment_retention_months', '24', 'ลบไฟล์แนบหลังกี่เดือน'],
  ['session_minutes', '30', 'อายุ session ของผู้ใช้ username'],
  ['company_name', '', 'ชื่อบริษัทที่แสดงในแอป'],
  ['attachments_folder_id', '', 'สร้างอัตโนมัติตอนตั้งค่า'],
  ['backups_folder_id', '', 'สร้างอัตโนมัติตอนตั้งค่า'],
  ['data_cutoff_date', '', 'วันตัดยอดของข้อมูลที่นำเข้า (ตั้งตอนนำเข้า)'],
  ['data_mode', 'EMPTY', 'EMPTY / TEST / LIVE']
];

var ROLES = { ADMIN: 'ADMIN', SUPER_ADMIN: 'SUPER_ADMIN', OWNER: 'OWNER' };
var STATUS = {
  PENDING: 'PENDING', APPROVED: 'APPROVED', REJECTED: 'REJECTED', AUTO_REJECTED: 'AUTO_REJECTED',
  CANCEL_REQUESTED: 'CANCEL_REQUESTED', CANCELLED: 'CANCELLED', ESCALATED: 'ESCALATED'
};

/**
 * ระบบลา — Util.gs
 * Date helpers work on 'yyyy-MM-dd' strings using UTC arithmetic, so results never
 * depend on the server's timezone or daylight saving.
 */

/** Any Sheets cell value (Date or text) -> 'yyyy-MM-dd', or '' if empty/invalid. */
function toIso(v) {
  if (v === null || v === undefined || v === '') return '';
  if (Object.prototype.toString.call(v) === '[object Date]') {
    if (isNaN(v.getTime())) return '';
    return Utilities.formatDate(v, TZ, 'yyyy-MM-dd');
  }
  var s = String(v).trim();
  var m = s.match(/^(\d{4})-(\d{1,2})-(\d{1,2})/);
  if (m) return isoFromParts(+m[1], +m[2], +m[3]);
  m = s.match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})$/); // dd/mm/yyyy
  if (m) return isoFromParts(+m[3], +m[2], +m[1]);
  return '';
}

function isoFromParts(y, mo, d) {
  var dt = new Date(Date.UTC(y, mo - 1, d));
  if (dt.getUTCFullYear() !== y || dt.getUTCMonth() !== mo - 1 || dt.getUTCDate() !== d) return '';
  return pad4(y) + '-' + pad2(mo) + '-' + pad2(d);
}
function pad2(n) { return (n < 10 ? '0' : '') + n; }
function pad4(n) { return ('000' + n).slice(-4); }

function isoParts(iso) { var p = iso.split('-'); return { y: +p[0], m: +p[1], d: +p[2] }; }
function isoToMs(iso) { var p = isoParts(iso); return Date.UTC(p.y, p.m - 1, p.d); }
function msToIso(ms) { var d = new Date(ms); return isoFromParts(d.getUTCFullYear(), d.getUTCMonth() + 1, d.getUTCDate()); }
function addDays(iso, n) { return msToIso(isoToMs(iso) + n * 86400000); }
function daysBetween(a, b) { return Math.round((isoToMs(b) - isoToMs(a)) / 86400000); }
/** 1 = Monday … 7 = Sunday */
function isoWeekday(iso) { var w = new Date(isoToMs(iso)).getUTCDay(); return w === 0 ? 7 : w; }

function todayIso() { return Utilities.formatDate(new Date(), TZ, 'yyyy-MM-dd'); }
function nowStamp() { return Utilities.formatDate(new Date(), TZ, "yyyy-MM-dd'T'HH:mm:ss"); }

/** Last day of a month (handles leap years). */
function daysInMonth(y, m) { return new Date(Date.UTC(y, m, 0)).getUTCDate(); }

/** Same month/day in year y; 29 Feb becomes 28 Feb in non-leap years. */
function anniversaryInYear(hireIso, y) {
  var h = isoParts(hireIso);
  return isoFromParts(y, h.m, Math.min(h.d, daysInMonth(y, h.m)));
}

/** Start of the employee's leave year containing dateIso (most recent work anniversary). */
function leaveYearStart(hireIso, dateIso) {
  if (dateIso < hireIso) return '';
  var y = isoParts(dateIso).y;
  var a = anniversaryInYear(hireIso, y);
  return a <= dateIso ? a : anniversaryInYear(hireIso, y - 1);
}

/** Whole months of service from hireIso to dateIso. */
function fullMonthsBetween(fromIso, toIso) {
  if (toIso < fromIso) return -1;
  var f = isoParts(fromIso), t = isoParts(toIso);
  var months = (t.y - f.y) * 12 + (t.m - f.m);
  var dayInTarget = Math.min(f.d, daysInMonth(t.y, t.m));
  if (t.d < dayInTarget) months--;
  return months;
}

/** Working dates between two dates inclusive. workDays: array of 1..7; holidays: {iso:true}. */
function workingDates(startIso, endIso, workDays, holidays) {
  var out = [];
  if (!startIso || !endIso || endIso < startIso) return out;
  for (var d = startIso; d <= endIso; d = addDays(d, 1)) {
    if (workDays.indexOf(isoWeekday(d)) !== -1 && !holidays[d]) out.push(d);
  }
  return out;
}

function newId(prefix) {
  var stamp = Utilities.formatDate(new Date(), TZ, 'yyMMddHHmmss');
  var rnd = Math.floor(Math.random() * 46656).toString(36).toUpperCase();
  return prefix + stamp + ('00' + rnd).slice(-3);
}

/** Salted, iterated SHA-256. Returns hex. */
function hashPassword(password, salt) {
  var value = salt + '|' + password;
  for (var i = 0; i < 2000; i++) {
    var bytes = Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256, value, Utilities.Charset.UTF_8);
    value = bytes.map(function (b) { return ('0' + (b & 0xff).toString(16)).slice(-2); }).join('');
  }
  return value;
}

function randomToken(len) {
  var chars = 'ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnpqrstuvwxyz23456789';
  var s = '';
  for (var i = 0; i < len; i++) s += chars.charAt(Math.floor(Math.random() * chars.length));
  return s;
}

function toBool(v) { return v === true || String(v).toUpperCase() === 'TRUE'; }
function toNum(v) { return (v === '' || v === null || v === undefined) ? null : Number(v); }
function str(v) { return (v === null || v === undefined) ? '' : String(v).trim(); }

/**
 * ระบบลา — Db.gs
 * Tiny table layer over the spreadsheet: each tab is a table, row 1 = headers.
 */

function db_() { return SpreadsheetApp.getActiveSpreadsheet(); }

function sheet_(name) {
  var sh = db_().getSheetByName(name);
  if (!sh) throw new Error('ไม่พบแผ่นงาน "' + name + '" — กรุณารัน "ตั้งค่าระบบครั้งแรก" ก่อน');
  return sh;
}

/** All rows of a tab as objects. Date columns come back as 'yyyy-MM-dd'. */
function readAll(name) {
  var sh = sheet_(name);
  var cols = SCHEMA[name];
  var last = sh.getLastRow();
  if (last < 2) return [];
  var values = sh.getRange(2, 1, last - 1, cols.length).getValues();
  var out = [];
  for (var i = 0; i < values.length; i++) {
    var row = values[i];
    if (row.every(function (v) { return v === ''; })) continue;
    var o = { _row: i + 2 };
    for (var c = 0; c < cols.length; c++) {
      var key = cols[c], v = row[c];
      o[key] = DATE_COLS.indexOf(key) !== -1 ? toIso(v) : v;
    }
    out.push(o);
  }
  return out;
}

function objToRow_(name, o) {
  return SCHEMA[name].map(function (k) {
    var v = o[k];
    if (v === undefined || v === null) return '';
    return v;
  });
}

function appendObjects(name, objs) {
  if (!objs.length) return;
  var sh = sheet_(name);
  var rows = objs.map(function (o) { return objToRow_(name, o); });
  sh.getRange(sh.getLastRow() + 1, 1, rows.length, rows[0].length).setValues(rows);
}

/** Delete all data rows (keeps headers). */
function clearTable(name) {
  var sh = sheet_(name);
  var last = sh.getLastRow();
  if (last >= 2) sh.getRange(2, 1, last - 1, sh.getMaxColumns()).clearContent();
}

/** Update the first row where keyCol === keyVal with the fields in patch. Returns the old object. */
function updateWhere(name, keyCol, keyVal, patch) {
  var rows = readAll(name);
  for (var i = 0; i < rows.length; i++) {
    if (String(rows[i][keyCol]) === String(keyVal)) {
      var before = JSON.parse(JSON.stringify(rows[i]));
      var merged = rows[i];
      Object.keys(patch).forEach(function (k) { merged[k] = patch[k]; });
      var sh = sheet_(name);
      sh.getRange(merged._row, 1, 1, SCHEMA[name].length).setValues([objToRow_(name, merged)]);
      return before;
    }
  }
  return null;
}

function getSettings() {
  var map = {};
  readAll(SHEETS.SETTINGS).forEach(function (r) { map[r.key] = str(r.value); });
  return map;
}

function setSetting(key, value) {
  var found = updateWhere(SHEETS.SETTINGS, 'key', key, { value: String(value) });
  if (!found) appendObjects(SHEETS.SETTINGS, [{ key: key, value: String(value), note: '' }]);
}

function audit(actor, role, action, entity, entityId, before, after) {
  appendObjects(SHEETS.AUDIT, [{
    at: nowStamp(), actor: actor, role: role, action: action, entity: entity, entity_id: entityId,
    before_json: before ? JSON.stringify(before).slice(0, 45000) : '',
    after_json: after ? JSON.stringify(after).slice(0, 45000) : ''
  }]);
}

/** Script lock wrapper: no two writes that check-then-save can interleave. */
function withLock(fn) {
  var lock = LockService.getScriptLock();
  if (!lock.tryLock(20000)) throw new Error('ระบบกำลังมีผู้ใช้งานพร้อมกัน กรุณาลองใหม่อีกครั้ง');
  try { return fn(); } finally { lock.releaseLock(); }
}

/**
 * ระบบลา — Rules.gs
 * The leave rules engine. Pure functions over a "state" snapshot — no sheet access here,
 * so every rule can be tested outside Apps Script.
 *
 * state = { employees[], departments[], types[], requests[], ledger[], holidays{iso:true},
 *           settings{}, today:'yyyy-MM-dd' }
 */

var ACTIVE_REQ = ['PENDING', 'ESCALATED', 'APPROVED', 'CANCEL_REQUESTED'];
var PENDING_REQ = ['PENDING', 'ESCALATED'];
var TAKEN_REQ = ['APPROVED', 'CANCEL_REQUESTED']; // counts as leave taken / slot occupied

function workDaysOf_(state) { return str(state.settings.work_days || '1,2,3,4,5').split(',').map(Number); }
function findEmp_(state, id) { return state.employees.filter(function (e) { return str(e.emp_id) === str(id); })[0] || null; }
function findDept_(state, id) { return state.departments.filter(function (d) { return str(d.dept_id) === str(id); })[0] || null; }
function findType_(state, id) { return state.types.filter(function (t) { return str(t.type_id) === str(id); })[0] || null; }
function findReq_(state, id) { return state.requests.filter(function (r) { return str(r.req_id) === str(id); })[0] || null; }
function empName(e) { return e ? (e.first_name + ' ' + e.last_name + (e.nickname ? ' (' + e.nickname + ')' : '')) : '-'; }

function reqDates_(state, r) { return workingDates(r.start_date, r.end_date, workDaysOf_(state), state.holidays); }

/** Working days of a request split by the employee's leave year. */
function splitByLeaveYear(state, emp, dates) {
  var by = {};
  dates.forEach(function (d) { var y = leaveYearStart(emp.hire_date, d); by[y] = (by[y] || 0) + 1; });
  return by;
}

/** Quota an employee is entitled to in a given leave year (0 if not yet eligible). */
function projectedGrant_(emp, type, lys) {
  var q = toNum(type.annual_quota);
  if (q === null) return null;
  return fullMonthsBetween(emp.hire_date, lys) >= Number(type.eligible_after_months || 0) ? q : 0;
}

/**
 * Balance of one type in one leave year.
 * granted: ledger GRANT/ADJUST(+); for a leave year that has not been granted yet, the projected quota.
 * used: approved/opening takes (negative ledger rows, net of reversals).
 * pending: working days of PENDING/ESCALATED requests in that leave year.
 */
function balanceFor(state, emp, typeId, lys, excludeReqId) {
  var type = findType_(state, typeId);
  if (!type || toNum(type.annual_quota) === null) return null;
  var granted = 0, used = 0, hasGrant = false;
  state.ledger.forEach(function (l) {
    if (str(l.emp_id) !== str(emp.emp_id) || str(l.type_id) !== typeId || l.leave_year_start !== lys) return;
    var d = Number(l.delta_days);
    if (l.kind === 'GRANT') { granted += d; hasGrant = true; }
    else if (l.kind === 'ADJUST') { if (d >= 0) granted += d; else used -= d; }
    else used -= d; // TAKE / OPENING_USED negative, REVERSE positive
  });
  if (!hasGrant) {
    var currentLys = leaveYearStart(emp.hire_date, state.today);
    if (lys >= currentLys) granted += projectedGrant_(emp, type, lys) || 0;
  }
  var pending = 0;
  state.requests.forEach(function (r) {
    if (str(r.emp_id) !== str(emp.emp_id) || str(r.type_id) !== typeId || PENDING_REQ.indexOf(r.status) === -1) return;
    if (excludeReqId && str(r.req_id) === str(excludeReqId)) return;
    var by = splitByLeaveYear(state, emp, reqDates_(state, r));
    pending += by[lys] || 0;
  });
  return { granted: granted, used: used, pending: pending, available: granted - used - pending };
}

/** Balances for the employee's current leave year, for the home screen. */
function balancesNow(state, emp) {
  var lys = leaveYearStart(emp.hire_date, state.today);
  return state.types.filter(function (t) { return toBool(t.active) && toNum(t.annual_quota) !== null; })
    .map(function (t) {
      var b = balanceFor(state, emp, str(t.type_id), lys);
      return { type_id: t.type_id, name_th: t.name_th, color: t.color, leave_year_start: lys,
        leave_year_end: addDays(anniversaryInYear(emp.hire_date, isoParts(lys).y + 1), -1),
        granted: b.granted, used: b.used, pending: b.pending, available: b.available };
    });
}

/** Dates in [from, to] where the department slot is already full (approved leave only). */
function takenDeptDates(state, deptId, fromIso, toIso, excludeReqId) {
  var max = Number((findDept_(state, deptId) || {}).max_concurrent || state.settings.dept_max_concurrent || 1);
  var count = {}, who = {};
  state.requests.forEach(function (r) {
    if (str(r.dept_id) !== str(deptId) || TAKEN_REQ.indexOf(r.status) === -1) return;
    if (excludeReqId && str(r.req_id) === str(excludeReqId)) return;
    var t = findType_(state, r.type_id);
    if (!t || !toBool(t.takes_slot)) return;
    if (r.end_date < fromIso || r.start_date > toIso) return;
    reqDates_(state, r).forEach(function (d) {
      if (d < fromIso || d > toIso) return;
      count[d] = (count[d] || 0) + 1;
      (who[d] = who[d] || []).push(r.emp_id);
    });
  });
  var full = Object.keys(count).filter(function (d) { return count[d] >= max; }).sort();
  return { full: full, who: who };
}

/** Who approves a request from this employee: the head, or SUPER_ADMIN if the requester is the head or the head is away. */
function approverFor(state, emp) {
  var dept = findDept_(state, emp.dept_id);
  if (!dept || !dept.head_emp_id || str(dept.head_emp_id) === str(emp.emp_id)) return 'SUPER_ADMIN';
  var head = findEmp_(state, dept.head_emp_id);
  if (!head || head.status !== 'ACTIVE') return 'SUPER_ADMIN';
  var headAway = state.requests.some(function (r) {
    return str(r.emp_id) === str(head.emp_id) && TAKEN_REQ.indexOf(r.status) !== -1 &&
      r.start_date <= state.today && r.end_date >= state.today;
  });
  return headAway ? 'SUPER_ADMIN' : str(head.emp_id);
}

/**
 * Check a new leave request. input = { type_id, start_date, end_date, reason, attachment_count }
 * opts = { bySuperAdmin: bool }  — super-admin filing on someone's behalf skips the rules (only basic validity).
 * Returns { ok, errors:[{code,msg}], warnings:[...], dates, byYear, needsDoc }
 */
function validateRequest(state, emp, input, opts) {
  opts = opts || {};
  var errors = [], warnings = [];
  function fail(code, msg, extra) { var e = { code: code, msg: msg }; if (extra) e.extra = extra; errors.push(e); }
  var res = { ok: false, errors: errors, warnings: warnings, dates: [], byYear: {}, needsDoc: false };

  // 1. employee
  if (!emp || emp.status !== 'ACTIVE') { fail('EMP_INACTIVE', 'ไม่พบพนักงานหรือพนักงานไม่ได้ทำงานอยู่'); return res; }
  if (!opts.bySuperAdmin && !emp.line_user_id) { fail('NOT_LINKED', 'ยังไม่ได้ผูกบัญชี LINE'); return res; }

  // 2. dates
  var s = toIso(input.start_date), e = toIso(input.end_date);
  if (!s || !e) { fail('BAD_DATE', 'วันที่ไม่ถูกต้อง'); return res; }
  if (e < s) { fail('BAD_RANGE', 'วันสุดท้ายต้องไม่ก่อนวันเริ่มลา'); return res; }
  var dates = workingDates(s, e, workDaysOf_(state), state.holidays);
  if (!dates.length) { fail('NO_WORKDAY', 'ช่วงที่เลือกไม่มีวันทำงาน'); return res; }
  res.dates = dates;
  res.byYear = splitByLeaveYear(state, emp, dates);

  var type = findType_(state, input.type_id);
  if (!type || !toBool(type.active)) { fail('BAD_TYPE', 'ประเภทการลาไม่ถูกต้อง'); return res; }

  // 5. own overlap (also checked for super-admin, as a warning)
  var overlap = state.requests.filter(function (r) {
    return str(r.emp_id) === str(emp.emp_id) && ACTIVE_REQ.indexOf(r.status) !== -1 && r.start_date <= e && r.end_date >= s;
  });

  var needsDocDays = toNum(type.doc_min_days);
  if (type.doc_rule === 'REQUIRED_IF_MIN_DAYS' && needsDocDays !== null && dates.length >= needsDocDays) res.needsDoc = true;
  if (type.doc_rule === 'REQUIRED') res.needsDoc = true;

  if (opts.bySuperAdmin) {
    if (overlap.length) warnings.push('ซ้อนกับใบลาเดิมของพนักงาน ' + overlap.map(function (r) { return r.req_id; }).join(', '));
    res.ok = true;
    return res;
  }

  // 3. self-service period, eligibility, max per request
  var minMonths = Number(state.settings.self_service_after_months || 12);
  if (fullMonthsBetween(emp.hire_date, state.today) < minMonths) {
    fail('SELF_SERVICE_LOCKED', 'ทำงานยังไม่ครบ ' + minMonths + ' เดือน กรุณาแจ้งผู้ดูแลระบบ (Super-admin) เพื่อบันทึกการลาแทน');
    return res;
  }
  if (fullMonthsBetween(emp.hire_date, s) < Number(type.eligible_after_months || 0)) {
    fail('NOT_ELIGIBLE', 'ยังไม่มีสิทธิ์' + type.name_th + ' (ต้องทำงานครบ ' + type.eligible_after_months + ' เดือน)');
  }
  var maxPer = toNum(type.max_days_per_request);
  if (maxPer !== null && dates.length > maxPer) fail('TOO_LONG', type.name_th + 'ได้ไม่เกิน ' + maxPer + ' วันต่อครั้ง');

  // 4. notice / filing window
  var notice = Number(type.notice_days || 0);
  if (notice > 0) {
    if (daysBetween(state.today, s) < notice) fail('NOTICE', type.name_th + 'ต้องแจ้งล่วงหน้าอย่างน้อย ' + notice + ' วัน (เริ่มได้ตั้งแต่ ' + addDays(state.today, notice) + ')');
  } else {
    var win = toNum(type.filing_window_days);
    if (win !== null && e < state.today) {
      var late = workingDates(addDays(e, 1), state.today, workDaysOf_(state), state.holidays).length;
      if (late > win) fail('FILING_LATE', 'ต้องยื่น' + type.name_th + 'ภายใน ' + win + ' วันทำงานหลังกลับมาทำงาน กรุณาแจ้งผู้ดูแลระบบ');
    }
  }

  // 5. own overlap
  if (overlap.length) fail('OVERLAP', 'ช่วงนี้มีใบลาของคุณอยู่แล้ว');

  // 6. balance per leave year
  if (toNum(type.annual_quota) !== null) {
    Object.keys(res.byYear).forEach(function (lys) {
      var b = balanceFor(state, emp, str(type.type_id), lys);
      if (b.available < res.byYear[lys]) {
        fail(type.type_id === 'SICK' ? 'SICK_OVER' : 'NO_BALANCE',
          type.name_th + 'คงเหลือ ' + Math.max(b.available, 0) + ' วัน (ขอ ' + res.byYear[lys] + ' วัน)' +
          (type.type_id === 'SICK' ? ' — ส่วนที่เกินให้ยื่นเป็นลาไม่รับค่าจ้าง' : ''),
          { available: Math.max(b.available, 0), lys: lys });
      }
    });
  }

  // 7. department slot
  if (toBool(type.blocked_by_slot)) {
    var taken = takenDeptDates(state, emp.dept_id, s, e);
    var clash = dates.filter(function (d) { return taken.full.indexOf(d) !== -1; });
    if (clash.length) fail('SLOT_TAKEN', 'แผนกมีผู้ลาแล้วในวันที่ ' + clash.join(', '), { dates: clash });
  }

  // 8. documents
  var att = Number(input.attachment_count || 0);
  if (type.doc_rule === 'REQUIRED' && att === 0) fail('DOC_REQUIRED', type.name_th + 'ต้องแนบเอกสารทุกครั้ง');
  if (res.needsDoc && att === 0 && type.doc_rule === 'REQUIRED_IF_MIN_DAYS')
    warnings.push('ลาตั้งแต่ ' + needsDocDays + ' วันขึ้นไปต้องแนบใบรับรองแพทย์ แนบภายหลังได้ แต่หัวหน้าจะอนุมัติไม่ได้จนกว่าจะแนบ');
  if (!str(input.reason)) fail('NO_REASON', 'กรุณาระบุเหตุผล');

  res.ok = errors.length === 0;
  return res;
}

/**
 * Re-check at approval time. Returns { ok, errors, autoReject:[req_id], doubleAbsence:[iso] }
 */
function validateApproval(state, req, attachmentCount) {
  var errors = [], emp = findEmp_(state, req.emp_id), type = findType_(state, req.type_id);
  var out = { ok: false, errors: errors, autoReject: [], doubleAbsence: [] };
  if (PENDING_REQ.indexOf(req.status) === -1) { errors.push({ code: 'BAD_STATUS', msg: 'ใบลานี้ไม่ได้รออนุมัติแล้ว' }); return out; }
  if (!emp || emp.status !== 'ACTIVE') { errors.push({ code: 'EMP_INACTIVE', msg: 'พนักงานไม่ได้ทำงานอยู่' }); return out; }
  var dates = reqDates_(state, req);
  var needsDoc = type.doc_rule === 'REQUIRED' ||
    (type.doc_rule === 'REQUIRED_IF_MIN_DAYS' && toNum(type.doc_min_days) !== null && dates.length >= Number(type.doc_min_days));
  if (needsDoc && !attachmentCount) errors.push({ code: 'DOC_MISSING', msg: 'ยังไม่ได้แนบเอกสาร — อนุมัติไม่ได้จนกว่าพนักงานจะแนบ' });

  if (toNum(type.annual_quota) !== null) {
    var by = splitByLeaveYear(state, emp, dates);
    Object.keys(by).forEach(function (lys) {
      var b = balanceFor(state, emp, str(type.type_id), lys, req.req_id);
      if (b.available < by[lys]) errors.push({ code: 'NO_BALANCE', msg: type.name_th + 'คงเหลือ ' + Math.max(b.available, 0) + ' วัน ไม่พอ' });
    });
  }
  var taken = takenDeptDates(state, req.dept_id, req.start_date, req.end_date, req.req_id);
  var clash = dates.filter(function (d) { return taken.full.indexOf(d) !== -1; });
  if (clash.length) {
    if (toBool(type.blocked_by_slot)) errors.push({ code: 'SLOT_TAKEN', msg: 'แผนกมีผู้ลาที่อนุมัติแล้วในวันที่ ' + clash.join(', ') });
    else out.doubleAbsence = clash;
  }
  out.ok = errors.length === 0;
  if (!out.ok) return out;

  // Once approved, which other pending planned requests in the dept lose their slot?
  if (toBool(type.takes_slot)) {
    var max = Number((findDept_(state, req.dept_id) || {}).max_concurrent || state.settings.dept_max_concurrent || 1);
    var after = takenDeptDates(state, req.dept_id, req.start_date, req.end_date, req.req_id);
    var fullAfter = {};
    dates.forEach(function (d) { if (((after.who[d] || []).length + 1) >= max) fullAfter[d] = true; });
    state.requests.forEach(function (r) {
      if (str(r.req_id) === str(req.req_id) || str(r.dept_id) !== str(req.dept_id) || PENDING_REQ.indexOf(r.status) === -1) return;
      var t = findType_(state, r.type_id);
      if (!t || !toBool(t.blocked_by_slot)) return;
      if (reqDates_(state, r).some(function (d) { return fullAfter[d]; })) out.autoReject.push(r.req_id);
    });
  }
  return out;
}

/** Calendar of the next n working days for a department. */
function deptCalendar(state, deptId, n) {
  var days = [], d = state.today, guard = 0;
  var staff = state.employees.filter(function (e) { return str(e.dept_id) === str(deptId) && e.status === 'ACTIVE'; });
  while (days.length < n && guard++ < 60) {
    if (workDaysOf_(state).indexOf(isoWeekday(d)) !== -1 && !state.holidays[d]) days.push(d);
    d = addDays(d, 1);
  }
  return days.map(function (day) {
    var away = state.requests.filter(function (r) {
      return str(r.dept_id) === str(deptId) && TAKEN_REQ.indexOf(r.status) !== -1 && r.start_date <= day && r.end_date >= day;
    }).map(function (r) {
      var e = findEmp_(state, r.emp_id), t = findType_(state, r.type_id);
      return { emp_id: r.emp_id, name: empName(e), type: t ? t.name_th : r.type_id, color: t ? t.color : '' };
    });
    var t = takenDeptDates(state, deptId, day, day);
    return { date: day, weekday: isoWeekday(day), away: away, available: staff.length - away.length,
      headcount: staff.length, slot_full: t.full.length > 0 };
  });
}

/**
 * ระบบลา — Service.gs
 * Every action that changes data: load state, check with Rules.gs, write, log, notify.
 * actor = { kind:'staff', emp } | { kind:'admin', user:{ username, role, full_name } }
 */

function AppError(code, msg) { this.code = code; this.message = msg; }
AppError.prototype = Object.create(Error.prototype);
function fail_(code, msg) { throw new AppError(code, msg); }

function loadState() {
  var holidays = {};
  readAll(SHEETS.HOLIDAYS).forEach(function (h) { if (h.date) holidays[h.date] = true; });
  return {
    employees: readAll(SHEETS.EMPLOYEES), departments: readAll(SHEETS.DEPARTMENTS),
    types: readAll(SHEETS.LEAVE_TYPES), requests: readAll(SHEETS.REQUESTS), ledger: readAll(SHEETS.LEDGER),
    attachments: readAll(SHEETS.ATTACHMENTS), holidays: holidays, settings: getSettings(), today: todayIso()
  };
}

function isAdminRole_(actor) { return actor.kind === 'admin' && (actor.user.role === 'ADMIN' || actor.user.role === 'SUPER_ADMIN'); }
function isSuperAdmin_(actor) { return actor.kind === 'admin' && actor.user.role === 'SUPER_ADMIN'; }
function actorId_(actor) { return actor.kind === 'staff' ? actor.emp.emp_id : actor.user.username; }
function actorRole_(actor) { return actor.kind === 'staff' ? 'EMPLOYEE' : actor.user.role; }

function attachmentsOf_(state, reqId) { return state.attachments.filter(function (a) { return str(a.req_id) === str(reqId); }); }

function writeTakes_(state, emp, req, by) {
  var dates = reqDates_(state, req), split = splitByLeaveYear(state, emp, dates), now = nowStamp();
  appendObjects(SHEETS.LEDGER, Object.keys(split).map(function (lys) {
    return { entry_id: newId('L'), emp_id: emp.emp_id, type_id: req.type_id, leave_year_start: lys,
      delta_days: -split[lys], kind: 'TAKE', req_id: req.req_id, by: by, at: now, note: '' };
  }));
}

function reverseTakes_(state, req, by, note) {
  var net = {};
  state.ledger.forEach(function (l) {
    if (str(l.req_id) !== str(req.req_id)) return;
    if (l.kind === 'TAKE' || l.kind === 'REVERSE') net[l.leave_year_start] = (net[l.leave_year_start] || 0) + Number(l.delta_days);
  });
  var now = nowStamp();
  appendObjects(SHEETS.LEDGER, Object.keys(net).filter(function (y) { return net[y] < 0; }).map(function (lys) {
    return { entry_id: newId('L'), emp_id: req.emp_id, type_id: req.type_id, leave_year_start: lys,
      delta_days: -net[lys], kind: 'REVERSE', req_id: req.req_id, by: by, at: now, note: note || '' };
  }));
}

function setReq_(req, patch, actor) {
  patch.updated_at = nowStamp();
  var before = updateWhere(SHEETS.REQUESTS, 'req_id', req.req_id, patch);
  Object.keys(patch).forEach(function (k) { req[k] = patch[k]; });
  audit(actorId_(actor), actorRole_(actor), 'REQUEST_' + (patch.status || 'UPDATE'), 'LeaveRequest', req.req_id, before, patch);
}

/** Claim uploaded files for a request (only files uploaded by this actor and not yet attached). */
function claimAttachments_(state, actor, reqId, attIds) {
  var mine = (attIds || []).filter(function (id) {
    var a = state.attachments.filter(function (x) { return str(x.att_id) === str(id); })[0];
    return a && !str(a.req_id) && str(a.uploaded_by) === str(actorId_(actor));
  });
  mine.forEach(function (id) { updateWhere(SHEETS.ATTACHMENTS, 'att_id', id, { req_id: reqId }); });
  return mine.length;
}

/* ------------------------------------------------------------------ submit */

function previewLeave(actor, input) {
  var state = loadState();
  var emp = actor.kind === 'staff' ? findEmp_(state, actor.emp.emp_id) : findEmp_(state, input.emp_id);
  return validateRequest(state, emp, input, { bySuperAdmin: actor.kind === 'admin' && isAdminRole_(actor) });
}

function submitLeave(actor, input, attIds) {
  return withLock(function () {
    var state = loadState();
    var onBehalf = actor.kind === 'admin';
    if (onBehalf && !isAdminRole_(actor)) fail_('FORBIDDEN', 'ไม่มีสิทธิ์บันทึกการลาแทน');
    var emp = onBehalf ? findEmp_(state, input.emp_id) : findEmp_(state, actor.emp.emp_id);
    var validAtt = (attIds || []).filter(function (id) {
      var a = state.attachments.filter(function (x) { return str(x.att_id) === str(id); })[0];
      return a && !str(a.req_id) && str(a.uploaded_by) === str(actorId_(actor));
    });
    input.attachment_count = validAtt.length;
    if (onBehalf && !str(input.reason)) fail_('NO_REASON', 'กรุณาระบุเหตุผลที่บันทึกแทน');
    var v = validateRequest(state, emp, input, { bySuperAdmin: onBehalf });
    if (!v.ok) return { ok: false, errors: v.errors, warnings: v.warnings };

    var now = nowStamp();
    var req = {
      req_id: newId('R'), emp_id: emp.emp_id, dept_id: emp.dept_id, type_id: input.type_id,
      start_date: toIso(input.start_date), end_date: toIso(input.end_date), working_days: v.dates.length,
      reason: str(input.reason), status: onBehalf ? 'APPROVED' : 'PENDING',
      approver_emp_id: onBehalf ? 'SUPER_ADMIN' : approverFor(state, emp),
      decided_by: onBehalf ? actor.user.username : '', decided_at: onBehalf ? now : '',
      decision_note: onBehalf ? 'บันทึกแทนโดย ' + actor.user.username : '',
      filed_by: onBehalf ? 'ADMIN:' + actor.user.username : 'SELF',
      leave_year_start: leaveYearStart(emp.hire_date, toIso(input.start_date)), created_at: now, updated_at: now
    };
    appendObjects(SHEETS.REQUESTS, [req]);
    state.requests.push(req);
    claimAttachments_(state, actor, req.req_id, validAtt);
    audit(actorId_(actor), actorRole_(actor), onBehalf ? 'REQUEST_FILED_ON_BEHALF' : 'REQUEST_SUBMIT', 'LeaveRequest', req.req_id, null, req);

    if (onBehalf) {
      writeTakes_(state, emp, req, actor.user.username);
      notifyEmployee_(state, req, 'FILED_ON_BEHALF');
      var dbl = takenDeptDates(state, req.dept_id, req.start_date, req.end_date, req.req_id).full
        .filter(function (d) { return v.dates.indexOf(d) !== -1; });
      if (dbl.length && toBool(findType_(state, req.type_id).takes_slot)) notifyDoubleAbsence_(state, req, dbl);
    } else {
      notifyApprover_(state, req, 'NEW_REQUEST');
    }
    return { ok: true, req: req, warnings: v.warnings };
  });
}

/* ------------------------------------------------------------------ decide */

function canDecide_(state, actor, req) {
  if (isAdminRole_(actor)) return true;
  if (actor.kind !== 'staff' || str(req.emp_id) === str(actor.emp.emp_id)) return false;
  if (str(req.approver_emp_id) === str(actor.emp.emp_id)) return true;
  var dept = findDept_(state, req.dept_id);
  return req.status === 'ESCALATED' && dept && str(dept.head_emp_id) === str(actor.emp.emp_id) && req.approver_emp_id !== 'SUPER_ADMIN';
}

function approveLeave(actor, reqId, note) {
  return withLock(function () {
    var state = loadState(), req = findReq_(state, reqId);
    if (!req) fail_('NOT_FOUND', 'ไม่พบใบลา');
    if (!canDecide_(state, actor, req)) fail_('FORBIDDEN', 'คุณไม่มีสิทธิ์อนุมัติใบลานี้');
    var check = validateApproval(state, req, attachmentsOf_(state, req.req_id).length);
    if (!check.ok) return { ok: false, errors: check.errors };
    var emp = findEmp_(state, req.emp_id);
    setReq_(req, { status: 'APPROVED', decided_by: actorId_(actor), decided_at: nowStamp(), decision_note: str(note) }, actor);
    writeTakes_(state, emp, req, actorId_(actor));
    notifyEmployee_(state, req, 'APPROVED');
    check.autoReject.forEach(function (id) {
      var other = findReq_(state, id);
      setReq_(other, { status: 'AUTO_REJECTED', decided_by: 'SYSTEM', decided_at: nowStamp(), decision_note: 'มีผู้ลาในแผนกแล้ว' }, actor);
      notifyEmployee_(state, other, 'AUTO_REJECTED');
    });
    if (check.doubleAbsence.length) notifyDoubleAbsence_(state, req, check.doubleAbsence);
    return { ok: true, req: req, autoRejected: check.autoReject };
  });
}

function rejectLeave(actor, reqId, reason) {
  if (!str(reason)) fail_('NO_REASON', 'กรุณาระบุเหตุผลที่ไม่อนุมัติ');
  return withLock(function () {
    var state = loadState(), req = findReq_(state, reqId);
    if (!req) fail_('NOT_FOUND', 'ไม่พบใบลา');
    if (!canDecide_(state, actor, req)) fail_('FORBIDDEN', 'คุณไม่มีสิทธิ์พิจารณาใบลานี้');
    if (PENDING_REQ.indexOf(req.status) === -1) fail_('BAD_STATUS', 'ใบลานี้ไม่ได้รออนุมัติแล้ว');
    setReq_(req, { status: 'REJECTED', decided_by: actorId_(actor), decided_at: nowStamp(), decision_note: str(reason) }, actor);
    notifyEmployee_(state, req, 'REJECTED');
    return { ok: true, req: req };
  });
}

/* ------------------------------------------------------------------ cancel */

function cancelLeave(actor, reqId, reason) {
  return withLock(function () {
    var state = loadState(), req = findReq_(state, reqId);
    if (!req) fail_('NOT_FOUND', 'ไม่พบใบลา');
    var admin = isAdminRole_(actor);
    var owner = actor.kind === 'staff' && str(req.emp_id) === str(actor.emp.emp_id);
    if (!admin && !owner) fail_('FORBIDDEN', 'ยกเลิกได้เฉพาะใบลาของตัวเอง');

    if (admin) {
      if (ACTIVE_REQ.indexOf(req.status) === -1) fail_('BAD_STATUS', 'ใบลานี้ไม่อยู่ในสถานะที่ยกเลิกได้');
      if (!str(reason)) fail_('NO_REASON', 'กรุณาระบุเหตุผล');
      var wasTaken = TAKEN_REQ.indexOf(req.status) !== -1;
      setReq_(req, { status: 'CANCELLED', decided_by: actorId_(actor), decided_at: nowStamp(), decision_note: 'ยกเลิกโดยผู้ดูแล: ' + reason }, actor);
      if (wasTaken) reverseTakes_(state, req, actorId_(actor), reason);
      notifyEmployee_(state, req, 'CANCELLED_BY_ADMIN');
      return { ok: true, req: req };
    }
    if (PENDING_REQ.indexOf(req.status) !== -1) {
      setReq_(req, { status: 'CANCELLED', decision_note: 'พนักงานยกเลิกเอง' }, actor);
      return { ok: true, req: req };
    }
    if (req.status === 'APPROVED') {
      if (req.start_date <= state.today) fail_('STARTED', 'ใบลาเริ่มแล้ว กรุณาแจ้งผู้ดูแลระบบเพื่อแก้ไข');
      setReq_(req, { status: 'CANCEL_REQUESTED', decision_note: str(reason) }, actor);
      notifyApprover_(state, req, 'CANCEL_REQUESTED');
      return { ok: true, req: req };
    }
    fail_('BAD_STATUS', 'ใบลานี้ยกเลิกไม่ได้');
  });
}

function decideCancel(actor, reqId, approve) {
  return withLock(function () {
    var state = loadState(), req = findReq_(state, reqId);
    if (!req) fail_('NOT_FOUND', 'ไม่พบใบลา');
    if (req.status !== 'CANCEL_REQUESTED') fail_('BAD_STATUS', 'ไม่มีคำขอยกเลิกค้างอยู่');
    var allowed = isAdminRole_(actor) || (actor.kind === 'staff' && str(actor.emp.emp_id) !== str(req.emp_id) &&
      (str(req.approver_emp_id) === str(actor.emp.emp_id) || str((findDept_(state, req.dept_id) || {}).head_emp_id) === str(actor.emp.emp_id)));
    if (!allowed) fail_('FORBIDDEN', 'คุณไม่มีสิทธิ์พิจารณาคำขอนี้');
    if (approve) {
      setReq_(req, { status: 'CANCELLED', decided_by: actorId_(actor), decided_at: nowStamp() }, actor);
      reverseTakes_(state, req, actorId_(actor), 'อนุมัติให้ยกเลิก');
      notifyEmployee_(state, req, 'CANCEL_APPROVED');
    } else {
      setReq_(req, { status: 'APPROVED' }, actor);
      notifyEmployee_(state, req, 'CANCEL_REFUSED');
    }
    return { ok: true, req: req };
  });
}

/* ------------------------------------------------------------------ admin */

function adjustBalance(actor, empId, typeId, delta, reason) {
  if (!isAdminRole_(actor)) fail_('FORBIDDEN', 'สำหรับผู้ดูแลระบบเท่านั้น');
  delta = Number(delta);
  if (!delta || Math.floor(delta) !== delta) fail_('BAD_VALUE', 'จำนวนวันต้องเป็นจำนวนเต็มและไม่เป็นศูนย์');
  if (!str(reason)) fail_('NO_REASON', 'กรุณาระบุเหตุผล');
  return withLock(function () {
    var state = loadState(), emp = findEmp_(state, empId), type = findType_(state, typeId);
    if (!emp || !type) fail_('NOT_FOUND', 'ไม่พบพนักงานหรือประเภทการลา');
    var lys = leaveYearStart(emp.hire_date, state.today);
    var row = { entry_id: newId('L'), emp_id: emp.emp_id, type_id: type.type_id, leave_year_start: lys, delta_days: delta,
      kind: 'ADJUST', req_id: '', by: actor.user.username, at: nowStamp(), note: reason };
    appendObjects(SHEETS.LEDGER, [row]);
    audit(actor.user.username, actor.user.role, 'BALANCE_ADJUST', 'Employee', emp.emp_id, null, row);
    pushToEmp_(state, emp, 'ADMIN_CHANGE', 'มีการปรับยอดวันลา', [
      ['ประเภท', type.name_th], ['ปรับ', (delta > 0 ? '+' : '') + delta + ' วัน'], ['เหตุผล', reason]], '');
    return { ok: true };
  });
}

/** Store an uploaded file (base64) in the private Attachments folder. */
function uploadAttachment(actor, name, mime, base64) {
  var allowed = ['image/jpeg', 'image/png', 'image/heic', 'application/pdf'];
  if (allowed.indexOf(mime) === -1) fail_('BAD_FILE', 'รองรับเฉพาะรูปภาพ (JPG, PNG) หรือ PDF');
  var bytes = Utilities.base64Decode(base64);
  if (bytes.length > 8 * 1024 * 1024) fail_('TOO_BIG', 'ไฟล์ใหญ่เกิน 8 MB');
  var folder = DriveApp.getFolderById(getSettings().attachments_folder_id);
  var file = folder.createFile(Utilities.newBlob(bytes, mime, newId('F') + '_' + str(name).replace(/[^\w.\-]/g, '_').slice(-60)));
  var row = { att_id: newId('A'), req_id: '', drive_file_id: file.getId(), mime: mime, size_kb: Math.ceil(bytes.length / 1024),
    uploaded_by: actorId_(actor), uploaded_at: nowStamp() };
  appendObjects(SHEETS.ATTACHMENTS, [row]);
  return { att_id: row.att_id };
}

function addAttachments(actor, reqId, attIds) {
  return withLock(function () {
    var state = loadState(), req = findReq_(state, reqId);
    if (!req) fail_('NOT_FOUND', 'ไม่พบใบลา');
    if (!(actor.kind === 'staff' && str(req.emp_id) === str(actor.emp.emp_id)) && !isAdminRole_(actor)) fail_('FORBIDDEN', 'ไม่มีสิทธิ์');
    var n = claimAttachments_(state, actor, reqId, attIds);
    if (n && PENDING_REQ.indexOf(req.status) !== -1) notifyApprover_(state, req, 'DOC_ADDED');
    return { ok: true, added: n };
  });
}

function canSeeRequest_(state, actor, req) {
  if (actor.kind === 'admin') return true; // admin, super-admin, owner
  if (str(req.emp_id) === str(actor.emp.emp_id)) return true;
  var dept = findDept_(state, req.dept_id);
  return str(req.approver_emp_id) === str(actor.emp.emp_id) || (dept && str(dept.head_emp_id) === str(actor.emp.emp_id));
}

function getAttachment(actor, attId) {
  var state = loadState();
  var a = state.attachments.filter(function (x) { return str(x.att_id) === str(attId); })[0];
  if (!a) fail_('NOT_FOUND', 'ไม่พบไฟล์');
  var req = findReq_(state, a.req_id);
  var own = str(a.uploaded_by) === str(actorId_(actor));
  if (!own && !(req && canSeeRequest_(state, actor, req) && !(actor.kind === 'admin' && actor.user.role === 'OWNER')))
    fail_('FORBIDDEN', 'ไม่มีสิทธิ์ดูไฟล์นี้');
  var blob = DriveApp.getFileById(a.drive_file_id).getBlob();
  return { mime: a.mime, base64: Utilities.base64Encode(blob.getBytes()) };
}

/** Request with everything an approver needs to decide. */
function requestDetail(actor, reqId) {
  var state = loadState(), req = findReq_(state, reqId);
  if (!req || !canSeeRequest_(state, actor, req)) fail_('NOT_FOUND', 'ไม่พบใบลา');
  var emp = findEmp_(state, req.emp_id), type = findType_(state, req.type_id);
  var atts = attachmentsOf_(state, req.req_id).map(function (a) { return { att_id: a.att_id, mime: a.mime, size_kb: a.size_kb }; });
  var out = { req: req, employee: { emp_id: emp.emp_id, name: empName(emp), dept_id: emp.dept_id, position: emp.position },
    type: { type_id: type.type_id, name_th: type.name_th, color: type.color }, attachments: atts,
    can_decide: PENDING_REQ.indexOf(req.status) !== -1 && canDecide_(state, actor, req) };
  if (out.can_decide) {
    var chk = validateApproval(state, req, atts.length);
    out.check = { ok: chk.ok, errors: chk.errors, will_auto_reject: chk.autoReject.length, double_absence: chk.doubleAbsence };
    if (toNum(type.annual_quota) !== null) {
      var b = balanceFor(state, emp, str(type.type_id), req.leave_year_start, req.req_id);
      out.balance_after = b ? b.available - Number(req.working_days) : null;
    }
  }
  return out;
}

/**
 * ระบบลา — Auth.gs
 * Staff: LINE ID token from the LIFF app, verified with LINE on the server (Script Property LINE_LOGIN_CHANNEL_ID).
 * Admin / Super-admin / Owner: username + password, server-side session kept in CacheService.
 */

function digestHex_(s) {
  return Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256, s, Utilities.Charset.UTF_8)
    .map(function (b) { return ('0' + (b & 0xff).toString(16)).slice(-2); }).join('');
}

/** Returns { sub, name } for a valid LINE ID token, else throws. Cached 10 minutes. */
function verifyLineIdToken(idToken) {
  if (!idToken) fail_('AUTH', 'กรุณาเข้าสู่ระบบด้วย LINE');
  var cache = CacheService.getScriptCache(), key = 'tok:' + digestHex_(idToken).slice(0, 40);
  var hit = cache.get(key);
  if (hit) return JSON.parse(hit);
  var channelId = prop_('LINE_LOGIN_CHANNEL_ID');
  if (!channelId) fail_('CONFIG', 'ระบบยังไม่ได้ตั้งค่า LINE_LOGIN_CHANNEL_ID');
  var res = UrlFetchApp.fetch('https://api.line.me/oauth2/v2.1/verify', {
    method: 'post', muteHttpExceptions: true, payload: { id_token: idToken, client_id: channelId }
  });
  if (res.getResponseCode() !== 200) fail_('AUTH', 'การเข้าสู่ระบบหมดอายุ กรุณาเปิดแอปใหม่');
  var j = JSON.parse(res.getContentText());
  var out = { sub: j.sub, name: j.name || '' };
  var ttl = Math.max(60, Math.min(600, (j.exp || 0) - Math.floor(Date.now() / 1000)));
  cache.put(key, JSON.stringify(out), ttl);
  return out;
}

/** Staff actor from an ID token. emp is null if this LINE account is not linked yet. */
function staffActor(idToken) {
  var who = verifyLineIdToken(idToken);
  var emp = readAll(SHEETS.EMPLOYEES).filter(function (e) { return str(e.line_user_id) === who.sub && e.status === 'ACTIVE'; })[0] || null;
  return { kind: 'staff', lineUserId: who.sub, lineName: who.name, emp: emp };
}

/** First-time link: employee ID + birth date must match the master record. 5 wrong tries per hour. */
function linkLine(idToken, empId, birthDate) {
  var who = verifyLineIdToken(idToken);
  var cache = CacheService.getScriptCache(), failKey = 'linkfail:' + who.sub;
  var fails = Number(cache.get(failKey) || 0);
  if (fails >= 5) fail_('LOCKED', 'ลองผิดหลายครั้ง กรุณารอ 1 ชั่วโมง หรือติดต่อผู้ดูแลระบบ');
  return withLock(function () {
    var emps = readAll(SHEETS.EMPLOYEES);
    var already = emps.filter(function (e) { return str(e.line_user_id) === who.sub; })[0];
    if (already && str(already.emp_id) !== str(empId)) fail_('ALREADY_LINKED', 'บัญชี LINE นี้ผูกกับรหัส ' + already.emp_id + ' แล้ว กรุณาติดต่อผู้ดูแลระบบ');
    var emp = emps.filter(function (e) { return str(e.emp_id).toUpperCase() === str(empId).toUpperCase(); })[0];
    if (!emp || emp.status !== 'ACTIVE' || emp.birth_date !== toIso(birthDate)) {
      cache.put(failKey, String(fails + 1), 3600);
      fail_('NO_MATCH', 'รหัสพนักงานหรือวันเกิดไม่ตรงกับข้อมูลบริษัท (เหลือ ' + (4 - fails) + ' ครั้ง)');
    }
    if (str(emp.line_user_id) && str(emp.line_user_id) !== who.sub) fail_('TAKEN', 'รหัสนี้ผูกกับ LINE อื่นแล้ว กรุณาติดต่อผู้ดูแลระบบ');
    updateWhere(SHEETS.EMPLOYEES, 'emp_id', emp.emp_id, { line_user_id: who.sub, line_linked_at: nowStamp(), updated_at: nowStamp() });
    audit(emp.emp_id, 'EMPLOYEE', 'LINE_LINKED', 'Employee', emp.emp_id, null, { line_name: who.name });
    cache.remove(failKey);
    return { ok: true, emp_id: emp.emp_id };
  });
}

/* ------------------------------------------------------------------ username sessions */

function sessionTtl_() { return Math.min(21600, Number(getSettings().session_minutes || 30) * 60); }

function adminLogin(username, password) {
  username = str(username);
  return withLock(function () {
    var u = readAll(SHEETS.ADMIN_USERS).filter(function (x) { return str(x.username).toLowerCase() === username.toLowerCase(); })[0];
    if (!u || !toBool(u.active)) fail_('BAD_LOGIN', 'ชื่อผู้ใช้หรือรหัสผ่านไม่ถูกต้อง');
    if (str(u.locked_until) && str(u.locked_until) > nowStamp()) fail_('LOCKED', 'บัญชีถูกล็อกชั่วคราว ลองใหม่หลัง ' + str(u.locked_until).slice(11, 16) + ' น.');
    if (hashPassword(password, str(u.salt)) !== str(u.password_hash)) {
      var n = Number(u.failed_logins || 0) + 1;
      var patch = { failed_logins: n };
      if (n >= 5) { patch.locked_until = Utilities.formatDate(new Date(Date.now() + 15 * 60000), TZ, "yyyy-MM-dd'T'HH:mm:ss"); patch.failed_logins = 0; }
      updateWhere(SHEETS.ADMIN_USERS, 'username', u.username, patch);
      audit(u.username, u.role, 'LOGIN_FAILED', 'AdminUser', u.username, null, null);
      fail_('BAD_LOGIN', 'ชื่อผู้ใช้หรือรหัสผ่านไม่ถูกต้อง');
    }
    updateWhere(SHEETS.ADMIN_USERS, 'username', u.username, { failed_logins: 0, locked_until: '' });
    var token = randomToken(40);
    var sess = { username: u.username, role: u.role, full_name: u.full_name, must_change: toBool(u.must_change_password) };
    CacheService.getScriptCache().put('sess:' + token, JSON.stringify(sess), sessionTtl_());
    audit(u.username, u.role, 'LOGIN', 'AdminUser', u.username, null, null);
    return { session: token, user: sess };
  });
}

function adminActor(session) {
  if (!session) fail_('AUTH', 'กรุณาเข้าสู่ระบบ');
  var cache = CacheService.getScriptCache(), raw = cache.get('sess:' + session);
  if (!raw) fail_('AUTH', 'หมดเวลาการใช้งาน กรุณาเข้าสู่ระบบใหม่');
  cache.put('sess:' + session, raw, sessionTtl_()); // sliding expiry
  return { kind: 'admin', user: JSON.parse(raw), session: session };
}

function adminLogout(actor) { CacheService.getScriptCache().remove('sess:' + actor.session); return { ok: true }; }

function changePassword(actor, oldPw, newPw) {
  if (str(newPw).length < 10) fail_('WEAK', 'รหัสผ่านใหม่ต้องยาวอย่างน้อย 10 ตัวอักษร');
  return withLock(function () {
    var u = readAll(SHEETS.ADMIN_USERS).filter(function (x) { return x.username === actor.user.username; })[0];
    if (!u || hashPassword(oldPw, str(u.salt)) !== str(u.password_hash)) fail_('BAD_LOGIN', 'รหัสผ่านเดิมไม่ถูกต้อง');
    var salt = randomToken(16);
    updateWhere(SHEETS.ADMIN_USERS, 'username', u.username, { password_hash: hashPassword(newPw, salt), salt: salt, must_change_password: false });
    actor.user.must_change = false;
    CacheService.getScriptCache().put('sess:' + actor.session, JSON.stringify(actor.user), sessionTtl_());
    audit(u.username, u.role, 'PASSWORD_CHANGED', 'AdminUser', u.username, null, null);
    return { ok: true };
  });
}

/** Link the LINE account of a logged-in admin user, so they receive LINE alerts. */
function linkAdminLine(actor, idToken) {
  var who = verifyLineIdToken(idToken);
  updateWhere(SHEETS.ADMIN_USERS, 'username', actor.user.username, { line_user_id: who.sub });
  audit(actor.user.username, actor.user.role, 'LINE_LINKED', 'AdminUser', actor.user.username, null, null);
  return { ok: true };
}

/**
 * ระบบลา — Line.gs
 * LINE push messages (Flex cards in Thai). Secrets come from Script Properties:
 *   LINE_CHANNEL_ACCESS_TOKEN (Messaging API), LIFF_ID
 * Every push is logged in the Notifications tab. A failed push never breaks the action that caused it.
 */

var TYPE_COLORS = { NEW_REQUEST: '#1F4E78', APPROVED: '#2E7D32', REJECTED: '#C62828', AUTO_REJECTED: '#C62828',
  ESCALATED: '#E65100', CANCEL_REQUESTED: '#6A1B9A', DOC_ADDED: '#1F4E78', CERT_REMINDER: '#E65100',
  ADMIN_CHANGE: '#455A64', DOUBLE_ABSENCE: '#E65100', PENDING_TODAY: '#E65100' };

function prop_(k) { return PropertiesService.getScriptProperties().getProperty(k) || ''; }

function liffUrl_(reqId) {
  var id = prop_('LIFF_ID');
  if (!id) return '';
  return 'https://liff.line.me/' + id + (reqId ? '?page=request&id=' + encodeURIComponent(reqId) : '');
}

function flexCard_(title, color, rows, buttonLabel, url) {
  var body = rows.map(function (r) {
    return { type: 'box', layout: 'baseline', spacing: 'sm', contents: [
      { type: 'text', text: r[0], size: 'sm', color: '#888888', flex: 3 },
      { type: 'text', text: String(r[1] === '' || r[1] === null || r[1] === undefined ? '-' : r[1]), size: 'sm', color: '#222222', flex: 7, wrap: true }] };
  });
  var bubble = {
    type: 'bubble', size: 'kilo',
    header: { type: 'box', layout: 'vertical', backgroundColor: color, paddingAll: '12px',
      contents: [{ type: 'text', text: title, color: '#FFFFFF', weight: 'bold', size: 'md', wrap: true }] },
    body: { type: 'box', layout: 'vertical', spacing: 'sm', contents: body }
  };
  if (url) bubble.footer = { type: 'box', layout: 'vertical', contents: [
    { type: 'button', style: 'primary', color: color, height: 'sm', action: { type: 'uri', label: buttonLabel || 'เปิดดู', uri: url } }] };
  return { type: 'flex', altText: title, contents: bubble };
}

/** Low-level push. Returns true on success. */
function linePush_(lineUserId, message, meta) {
  var log = { at: nowStamp(), to_emp_id: meta.to || '', template: meta.template || '', req_id: meta.req_id || '', status: '', error: '' };
  try {
    var token = prop_('LINE_CHANNEL_ACCESS_TOKEN');
    if (!token) throw new Error('ยังไม่ได้ตั้งค่า LINE_CHANNEL_ACCESS_TOKEN');
    if (!lineUserId) throw new Error('ผู้รับยังไม่ได้ผูก LINE');
    var res = UrlFetchApp.fetch('https://api.line.me/v2/bot/message/push', {
      method: 'post', contentType: 'application/json', muteHttpExceptions: true,
      headers: { Authorization: 'Bearer ' + token },
      payload: JSON.stringify({ to: lineUserId, messages: [message] })
    });
    if (res.getResponseCode() !== 200) throw new Error('LINE ' + res.getResponseCode() + ': ' + res.getContentText().slice(0, 300));
    log.status = 'SENT';
    return true;
  } catch (e) {
    log.status = 'FAILED'; log.error = String(e.message || e).slice(0, 500);
    return false;
  } finally {
    try { appendObjects(SHEETS.NOTIFICATIONS, [log]); } catch (ignore) { }
  }
}

function pushToEmp_(state, emp, template, title, rows, reqId) {
  if (!emp) return;
  linePush_(emp.line_user_id, flexCard_(title, TYPE_COLORS[template] || '#1F4E78', rows, 'เปิดในแอป', liffUrl_(reqId)),
    { to: emp.emp_id, template: template, req_id: reqId });
}

/** Admin-side recipients (username accounts with a linked LINE). roles: array of role names. */
function pushToAdmins_(roles, template, title, rows, reqId) {
  readAll(SHEETS.ADMIN_USERS).forEach(function (u) {
    if (!toBool(u.active) || roles.indexOf(u.role) === -1 || !str(u.line_user_id)) return;
    linePush_(str(u.line_user_id), flexCard_(title, TYPE_COLORS[template] || '#1F4E78', rows, 'เปิดในแอป', liffUrl_(reqId)),
      { to: 'admin:' + u.username, template: template, req_id: reqId });
  });
}

function reqRows_(state, req, extra) {
  var emp = findEmp_(state, req.emp_id), type = findType_(state, req.type_id), dept = findDept_(state, req.dept_id);
  var dateText = req.start_date === req.end_date ? thaiDate(req.start_date) : thaiDate(req.start_date) + ' – ' + thaiDate(req.end_date);
  var rows = [['พนักงาน', empName(emp)], ['แผนก', dept ? dept.name : req.dept_id], ['ประเภท', type ? type.name_th : req.type_id],
    ['วันที่', dateText], ['จำนวน', req.working_days + ' วันทำงาน']];
  return rows.concat(extra || []);
}

function notifyApprover_(state, req, template) {
  var titles = { NEW_REQUEST: 'มีใบลารออนุมัติ', CANCEL_REQUESTED: 'ขอยกเลิกใบลาที่อนุมัติแล้ว', DOC_ADDED: 'พนักงานแนบเอกสารเพิ่มแล้ว', ESCALATED: 'ใบลาค้างอนุมัติเกินกำหนด' };
  var extra = [['เหตุผล', req.reason]];
  if (template === 'CANCEL_REQUESTED') extra = [['เหตุผลยกเลิก', req.decision_note]];
  var rows = reqRows_(state, req, extra);
  if (req.approver_emp_id === 'SUPER_ADMIN' || template === 'ESCALATED') pushToAdmins_(['SUPER_ADMIN'], template, titles[template], rows, req.req_id);
  if (req.approver_emp_id !== 'SUPER_ADMIN') pushToEmp_(state, findEmp_(state, req.approver_emp_id), template, titles[template], rows, req.req_id);
}

function notifyEmployee_(state, req, template) {
  var map = {
    APPROVED: ['อนุมัติใบลาแล้ว', 'APPROVED'], REJECTED: ['ไม่อนุมัติใบลา', 'REJECTED'],
    AUTO_REJECTED: ['ใบลาไม่ผ่าน: แผนกมีผู้ลาแล้ว', 'AUTO_REJECTED'],
    CANCELLED_BY_ADMIN: ['ใบลาถูกยกเลิกโดยผู้ดูแลระบบ', 'ADMIN_CHANGE'], FILED_ON_BEHALF: ['ผู้ดูแลระบบบันทึกการลาให้คุณแล้ว', 'ADMIN_CHANGE'],
    CANCEL_APPROVED: ['ยกเลิกใบลาเรียบร้อย คืนวันลาแล้ว', 'APPROVED'], CANCEL_REFUSED: ['ไม่อนุมัติการยกเลิก ใบลายังมีผล', 'REJECTED'],
    CERT_REMINDER: ['กรุณาแนบใบรับรองแพทย์', 'CERT_REMINDER']
  };
  var m = map[template];
  var extra = [];
  if (req.decision_note) extra.push(['หมายเหตุ', req.decision_note]);
  if (template === 'AUTO_REJECTED') extra.push(['แนะนำ', 'เลือกวันอื่นที่ยังว่างในแอป']);
  pushToEmp_(state, findEmp_(state, req.emp_id), m[1], m[0], reqRows_(state, req, extra), req.req_id);
}

function notifyDoubleAbsence_(state, req, dates) {
  var rows = reqRows_(state, req, [['วันที่ซ้อน', dates.map(thaiDate).join(', ')]]);
  var dept = findDept_(state, req.dept_id);
  if (dept && str(dept.head_emp_id) !== str(req.emp_id)) pushToEmp_(state, findEmp_(state, dept.head_emp_id), 'DOUBLE_ABSENCE', 'แผนกมีคนลาซ้อนกัน', rows, req.req_id);
  pushToAdmins_(['ADMIN', 'SUPER_ADMIN'], 'DOUBLE_ABSENCE', 'แผนกมีคนลาซ้อนกัน', rows, req.req_id);
}

var THAI_MONTHS = ['ม.ค.', 'ก.พ.', 'มี.ค.', 'เม.ย.', 'พ.ค.', 'มิ.ย.', 'ก.ค.', 'ส.ค.', 'ก.ย.', 'ต.ค.', 'พ.ย.', 'ธ.ค.'];
/** '2026-11-12' -> '12 พ.ย. 69' (Buddhist year, short) */
function thaiDate(iso) {
  if (!iso) return '';
  var p = isoParts(iso);
  return p.d + ' ' + THAI_MONTHS[p.m - 1] + ' ' + String(p.y + 543).slice(2);
}

/** Menu: check the LINE settings and send a test message to an employee who has linked LINE. */
function testLineSetup() {
  var problems = [];
  ['LINE_CHANNEL_ACCESS_TOKEN', 'LINE_LOGIN_CHANNEL_ID', 'LIFF_ID'].forEach(function (k) { if (!prop_(k)) problems.push('ยังไม่ได้ใส่ ' + k); });
  if (prop_('LINE_CHANNEL_ACCESS_TOKEN')) {
    var r = UrlFetchApp.fetch('https://api.line.me/v2/bot/info', { headers: { Authorization: 'Bearer ' + prop_('LINE_CHANNEL_ACCESS_TOKEN') }, muteHttpExceptions: true });
    if (r.getResponseCode() === 200) problems.push('✓ Access token ใช้ได้ (OA: ' + JSON.parse(r.getContentText()).displayName + ')');
    else problems.push('✗ Access token ใช้ไม่ได้ (' + r.getResponseCode() + ')');
  }
  notify_('ตรวจการตั้งค่า LINE', problems.join('\n') || 'ครบถ้วน');
}

/**
 * ระบบลา — Api.gs
 * JSON API for the web app. Deployed as: Web app · Execute as: Me · Who has access: Anyone.
 * Request:  POST (Content-Type text/plain, to avoid CORS preflight)
 *           { action, idToken?  (staff, from LIFF), session? (username users), data:{...} }
 * Response: { ok:true, data } | { ok:false, error:{ code, msg } }
 */

var API_VERSION = '2.0';

function doGet() { return json_({ ok: true, data: { service: 'leave-system', version: API_VERSION, time: nowStamp() } }); }

function doPost(e) {
  var body = {};
  try {
    body = JSON.parse((e && e.postData && e.postData.contents) || '{}');
    var route = ROUTES[body.action];
    if (!route) fail_('BAD_ACTION', 'ไม่รู้จักคำสั่ง ' + body.action);
    var actor = null;
    if (route.auth === 'staff' || route.auth === 'line') {
      actor = staffActor(body.idToken);
      if (route.auth === 'staff' && !actor.emp) fail_('NOT_LINKED', 'ยังไม่ได้ผูกบัญชี LINE กับรหัสพนักงาน');
    } else if (route.auth === 'admin' || route.auth === 'any') {
      if (route.auth === 'any' && body.idToken && !body.session) {
        actor = staffActor(body.idToken);
        if (!actor.emp) fail_('NOT_LINKED', 'ยังไม่ได้ผูกบัญชี LINE');
      } else {
        actor = adminActor(body.session);
        if (actor.user.must_change && body.action !== 'changePassword' && body.action !== 'logout')
          fail_('MUST_CHANGE_PASSWORD', 'กรุณาเปลี่ยนรหัสผ่านก่อนใช้งาน');
        if (route.roles && route.roles.indexOf(actor.user.role) === -1) fail_('FORBIDDEN', 'บัญชีนี้ไม่มีสิทธิ์ใช้งานส่วนนี้');
      }
    }
    return json_({ ok: true, data: route.fn(actor, body.data || {}, body) });
  } catch (err) {
    var code = err instanceof AppError ? err.code : 'SERVER';
    var msg = err instanceof AppError ? err.message : 'เกิดข้อผิดพลาดในระบบ กรุณาลองใหม่';
    if (!(err instanceof AppError)) {
      console.error(err && err.stack || err);
      try { audit('system', 'SYSTEM', 'API_ERROR', body.action || '', '', null, { error: String(err && err.message || err) }); } catch (ignore) { }
    }
    return json_({ ok: false, error: { code: code, msg: msg } });
  }
}

function json_(o) { return ContentService.createTextOutput(JSON.stringify(o)).setMimeType(ContentService.MimeType.JSON); }

var ADMINS = ['ADMIN', 'SUPER_ADMIN'];
var ALL_USERS = ['ADMIN', 'SUPER_ADMIN', 'OWNER'];

var ROUTES = {
  // ---- staff (LINE)
  me: { auth: 'line', fn: apiMe_ },
  link: { auth: 'line', fn: function (a, d, b) { return linkLine(b.idToken, d.emp_id, d.birth_date); } },
  preview: { auth: 'staff', fn: function (a, d) { return previewLeave(a, d); } },
  takenDates: { auth: 'staff', fn: apiTakenDates_ },
  submit: { auth: 'staff', fn: function (a, d) { return submitLeave(a, d.input || {}, d.att_ids); } },
  myRequests: { auth: 'staff', fn: apiMyRequests_ },
  deptCalendar: { auth: 'any', fn: apiDeptCalendar_ },
  inbox: { auth: 'any', fn: apiInbox_ },

  // ---- shared (staff or username users)
  upload: { auth: 'any', fn: function (a, d) { return uploadAttachment(a, d.name, d.mime, d.base64); } },
  addAttachments: { auth: 'any', fn: function (a, d) { return addAttachments(a, d.req_id, d.att_ids); } },
  attachment: { auth: 'any', fn: function (a, d) { return getAttachment(a, d.att_id); } },
  request: { auth: 'any', fn: function (a, d) { return requestDetail(a, d.req_id); } },
  approve: { auth: 'any', roles: ADMINS, fn: function (a, d) { return approveLeave(a, d.req_id, d.note); } },
  reject: { auth: 'any', roles: ADMINS, fn: function (a, d) { return rejectLeave(a, d.req_id, d.reason); } },
  cancel: { auth: 'any', roles: ADMINS, fn: function (a, d) { return cancelLeave(a, d.req_id, d.reason); } },
  decideCancel: { auth: 'any', roles: ADMINS, fn: function (a, d) { return decideCancel(a, d.req_id, !!d.approve); } },

  // ---- username users
  login: { auth: 'public', fn: function (a, d) { return adminLogin(d.username, d.password); } },
  logout: { auth: 'admin', fn: function (a) { return adminLogout(a); } },
  changePassword: { auth: 'admin', fn: function (a, d) { return changePassword(a, d.old_password, d.new_password); } },
  linkAdminLine: { auth: 'admin', fn: function (a, d) { return linkAdminLine(a, d.idToken); } },
  adminMe: { auth: 'admin', fn: function (a) { return { user: a.user, settings: publicSettings_(getSettings()) }; } },
  fileOnBehalf: { auth: 'admin', roles: ADMINS, fn: function (a, d) { return submitLeave(a, d.input || {}, d.att_ids); } },
  previewOnBehalf: { auth: 'admin', roles: ADMINS, fn: function (a, d) { return previewLeave(a, d); } },
  adjustBalance: { auth: 'admin', roles: ADMINS, fn: function (a, d) { return adjustBalance(a, d.emp_id, d.type_id, d.delta, d.reason); } },
  employees: { auth: 'admin', roles: ALL_USERS, fn: apiEmployees_ },
  employeeBalances: { auth: 'admin', roles: ALL_USERS, fn: apiEmployeeBalances_ },
  requests: { auth: 'admin', roles: ALL_USERS, fn: apiListRequests_ }
};

/* ------------------------------------------------------------------ handlers */

function publicSettings_(s) {
  return { company_name: s.company_name, work_days: s.work_days, self_service_after_months: s.self_service_after_months, data_mode: s.data_mode };
}

function typeForClient_(t) {
  return { type_id: t.type_id, name_th: t.name_th, color: t.color, annual_quota: toNum(t.annual_quota),
    notice_days: Number(t.notice_days || 0), doc_rule: t.doc_rule, doc_min_days: toNum(t.doc_min_days),
    eligible_after_months: Number(t.eligible_after_months || 0), blocked_by_slot: toBool(t.blocked_by_slot),
    max_days_per_request: toNum(t.max_days_per_request), paid_note: t.paid_note };
}

function reqForClient_(state, r) {
  var t = findType_(state, r.type_id), e = findEmp_(state, r.emp_id);
  return { req_id: r.req_id, emp_id: r.emp_id, name: empName(e), dept_id: r.dept_id, type_id: r.type_id,
    type_name: t ? t.name_th : r.type_id, color: t ? t.color : '', start_date: r.start_date, end_date: r.end_date,
    working_days: r.working_days, reason: r.reason, status: r.status, decision_note: r.decision_note,
    decided_at: r.decided_at, created_at: r.created_at, attachments: attachmentsOf_(state, r.req_id).length };
}

function apiMe_(actor) {
  if (!actor.emp) return { linked: false, line_name: actor.lineName, settings: publicSettings_(getSettings()) };
  var state = loadState(), emp = findEmp_(state, actor.emp.emp_id), dept = findDept_(state, emp.dept_id);
  var isHead = state.departments.some(function (d) { return str(d.head_emp_id) === str(emp.emp_id); });
  var minMonths = Number(state.settings.self_service_after_months || 12);
  var inboxCount = !isHead ? 0 : state.requests.filter(function (r) {
    return ['PENDING', 'ESCALATED', 'CANCEL_REQUESTED'].indexOf(r.status) !== -1 && str(r.approver_emp_id) === str(emp.emp_id);
  }).length;
  return {
    linked: true, today: state.today,
    employee: { emp_id: emp.emp_id, name: empName(emp), first_name: emp.first_name, dept_id: emp.dept_id,
      dept_name: dept ? dept.name : '', position: emp.position, hire_date: emp.hire_date },
    is_head: isHead, inbox_count: inboxCount,
    self_service: fullMonthsBetween(emp.hire_date, state.today) >= minMonths, self_service_after_months: minMonths,
    balances: balancesNow(state, emp),
    types: state.types.filter(function (t) { return toBool(t.active); }).map(typeForClient_),
    holidays: Object.keys(state.holidays).filter(function (d) { return d >= state.today; }).sort(),
    settings: publicSettings_(state.settings)
  };
}

function apiTakenDates_(actor, d) {
  var state = loadState();
  var from = toIso(d.from) || state.today, to = toIso(d.to) || addDays(from, 120);
  return { full: takenDeptDates(state, actor.emp.dept_id, from, to).full };
}

function apiMyRequests_(actor) {
  var state = loadState();
  return state.requests.filter(function (r) { return str(r.emp_id) === str(actor.emp.emp_id); })
    .sort(function (a, b) { return a.start_date < b.start_date ? 1 : -1; })
    .slice(0, 100).map(function (r) { return reqForClient_(state, r); });
}

function apiDeptCalendar_(actor, d) {
  var state = loadState(), n = Math.min(Number(d.days || 7), 31);
  if (actor.kind === 'staff') return [{ dept_id: actor.emp.dept_id, name: (findDept_(state, actor.emp.dept_id) || {}).name, days: deptCalendar(state, actor.emp.dept_id, n) }];
  return state.departments.filter(function (x) { return toBool(x.active); }).map(function (x) {
    return { dept_id: x.dept_id, name: x.name, days: deptCalendar(state, x.dept_id, n) };
  });
}

function apiInbox_(actor) {
  var state = loadState(), open = ['PENDING', 'ESCALATED', 'CANCEL_REQUESTED'];
  var list = state.requests.filter(function (r) {
    if (open.indexOf(r.status) === -1) return false;
    if (actor.kind === 'staff') return str(r.approver_emp_id) === str(actor.emp.emp_id) && str(r.emp_id) !== str(actor.emp.emp_id);
    // Super-admin also holds Admin rights (for now), so both see every open request.
    return actor.user.role === 'SUPER_ADMIN' || actor.user.role === 'ADMIN';
  });
  return list.sort(function (a, b) { return a.created_at < b.created_at ? -1 : 1; }).map(function (r) {
    var o = reqForClient_(state, r);
    o.waiting_hours = Math.floor((Date.now() - new Date(r.created_at + '+07:00').getTime()) / 3600000);
    o.for_super_admin = r.approver_emp_id === 'SUPER_ADMIN';
    return o;
  });
}

function apiEmployees_(actor) {
  var state = loadState();
  return state.employees.map(function (e) {
    var dept = findDept_(state, e.dept_id);
    return { emp_id: e.emp_id, name: empName(e), dept_id: e.dept_id, dept_name: dept ? dept.name : '', position: e.position,
      hire_date: e.hire_date, status: e.status, line_linked: !!str(e.line_user_id),
      is_head: state.departments.some(function (d) { return str(d.head_emp_id) === str(e.emp_id); }) };
  });
}

function apiEmployeeBalances_(actor, d) {
  var state = loadState(), emp = findEmp_(state, d.emp_id);
  if (!emp) fail_('NOT_FOUND', 'ไม่พบพนักงาน');
  return { emp_id: emp.emp_id, name: empName(emp), balances: balancesNow(state, emp),
    ledger: state.ledger.filter(function (l) { return str(l.emp_id) === str(emp.emp_id); }) };
}

function apiListRequests_(actor, d) {
  var state = loadState();
  return state.requests.filter(function (r) {
    if (d.dept_id && str(r.dept_id) !== str(d.dept_id)) return false;
    if (d.emp_id && str(r.emp_id) !== str(d.emp_id)) return false;
    if (d.status && r.status !== d.status) return false;
    if (d.from && r.end_date < toIso(d.from)) return false;
    if (d.to && r.start_date > toIso(d.to)) return false;
    return true;
  }).sort(function (a, b) { return a.start_date < b.start_date ? 1 : -1; }).slice(0, 1000)
    .map(function (r) { return reqForClient_(state, r); });
}

/**
 * ระบบลา — Jobs.gs
 * Scheduled jobs. Install once from the menu: ระบบลา > ติดตั้งงานอัตโนมัติ
 *   nightlyJob  ~00:30  anniversary grants, resignations, backup
 *   hourlyJob   hourly  24 h escalation (08:00–18:59 only)
 *   morningJob  ~08:00  certificate reminders, planned leave still pending on its start day
 */

function installTriggers() {
  var handlers = ['nightlyJob', 'hourlyJob', 'morningJob'];
  ScriptApp.getProjectTriggers().forEach(function (t) {
    if (handlers.indexOf(t.getHandlerFunction()) !== -1) ScriptApp.deleteTrigger(t);
  });
  ScriptApp.newTrigger('nightlyJob').timeBased().everyDays(1).atHour(0).nearMinute(30).inTimezone(TZ).create();
  ScriptApp.newTrigger('hourlyJob').timeBased().everyHours(1).create();
  ScriptApp.newTrigger('morningJob').timeBased().everyDays(1).atHour(8).inTimezone(TZ).create();
  audit('system', 'SYSTEM', 'TRIGGERS_INSTALLED', 'Project', '', null, { handlers: handlers });
  notify_('ติดตั้งงานอัตโนมัติแล้ว', 'งานกลางคืน 00:30 · ตรวจใบลาค้างทุกชั่วโมง · เตือนตอน 08:00');
}

/* ------------------------------------------------------------------ nightly */

function nightlyJob() {
  var out = {};
  try { out.grants = ensureGrants_(); } catch (e) { out.grantsError = String(e); }
  try { out.resigned = handleResignations_(); } catch (e) { out.resignError = String(e); }
  try { out.backup = backupSpreadsheet_(); } catch (e) { out.backupError = String(e); }
  audit('system', 'SYSTEM', 'NIGHTLY_JOB', 'Jobs', todayIso(), null, out);
}

/**
 * Make sure every active employee has this leave year's quota. Idempotent: it only adds a
 * GRANT when none exists for (employee, type, leave year), so a missed night is caught up next time.
 * The previous year's leftover simply expires (no carry-over) because balances are per leave year.
 */
function ensureGrants_() {
  return withLock(function () {
    var state = loadState(), have = {}, rows = [], now = nowStamp();
    state.ledger.forEach(function (l) { if (l.kind === 'GRANT') have[l.emp_id + '|' + l.type_id + '|' + l.leave_year_start] = true; });
    var quotaTypes = state.types.filter(function (t) { return toBool(t.active) && toNum(t.annual_quota) !== null; });
    state.employees.forEach(function (e) {
      if (e.status !== 'ACTIVE' || !e.hire_date || e.hire_date > state.today) return;
      var lys = leaveYearStart(e.hire_date, state.today);
      quotaTypes.forEach(function (t) {
        var q = projectedGrant_(e, t, lys);
        if (!q || have[e.emp_id + '|' + t.type_id + '|' + lys]) return;
        rows.push({ entry_id: newId('L'), emp_id: e.emp_id, type_id: t.type_id, leave_year_start: lys, delta_days: q,
          kind: 'GRANT', req_id: '', by: 'SYSTEM', at: now, note: 'สิทธิ์ปีการลา ' + lys });
      });
    });
    appendObjects(SHEETS.LEDGER, rows);
    return rows.length;
  });
}

/** Cancel open or approved leave that falls after an employee's resignation date. */
function handleResignations_() {
  var n = 0, sys = { kind: 'admin', user: { username: 'SYSTEM', role: 'SUPER_ADMIN' } };
  withLock(function () {
    var state = loadState();
    state.employees.forEach(function (e) {
      if (e.status !== 'RESIGNED' || !e.resign_date) return;
      state.requests.forEach(function (r) {
        if (str(r.emp_id) !== str(e.emp_id) || ACTIVE_REQ.indexOf(r.status) === -1 || r.start_date <= e.resign_date) return;
        var wasTaken = TAKEN_REQ.indexOf(r.status) !== -1;
        setReq_(r, { status: 'CANCELLED', decided_by: 'SYSTEM', decided_at: nowStamp(), decision_note: 'พนักงานลาออก' }, sys);
        if (wasTaken) reverseTakes_(state, r, 'SYSTEM', 'พนักงานลาออก');
        n++;
      });
    });
  });
  return n;
}

/** Copy the spreadsheet into Backups/ and keep the last 30 days. */
function backupSpreadsheet_() {
  var s = getSettings();
  if (!s.backups_folder_id) return 'no folder';
  var folder = DriveApp.getFolderById(s.backups_folder_id);
  DriveApp.getFileById(db_().getId()).makeCopy('Backup ' + todayIso(), folder);
  var cutoff = Date.now() - 30 * 86400000, removed = 0, files = folder.getFiles();
  while (files.hasNext()) {
    var f = files.next();
    if (f.getName().indexOf('Backup ') === 0 && f.getDateCreated().getTime() < cutoff) { f.setTrashed(true); removed++; }
  }
  return 'ok, removed ' + removed;
}

/* ------------------------------------------------------------------ hourly */

function hourlyJob() {
  var hour = Number(Utilities.formatDate(new Date(), TZ, 'H'));
  if (hour < 8 || hour > 18) return;
  var hours = Number(getSettings().escalation_hours || 24), escalated = [];
  var sys = { kind: 'admin', user: { username: 'SYSTEM', role: 'SUPER_ADMIN' } };
  withLock(function () {
    var state = loadState();
    state.requests.forEach(function (r) {
      if (r.status !== 'PENDING' || r.approver_emp_id === 'SUPER_ADMIN') return;
      var age = (Date.now() - new Date(r.created_at + '+07:00').getTime()) / 3600000;
      if (age < hours) return;
      setReq_(r, { status: 'ESCALATED' }, sys);
      escalated.push(r);
    });
    escalated.forEach(function (r) { notifyApprover_(state, r, 'ESCALATED'); });
  });
  if (escalated.length) audit('system', 'SYSTEM', 'ESCALATION', 'Jobs', '', null, { count: escalated.length });
}

/* ------------------------------------------------------------------ morning */

function morningJob() {
  var state = loadState();
  var maxReminders = Number(state.settings.cert_reminder_max || 3);
  var sent = {};
  readAll(SHEETS.NOTIFICATIONS).forEach(function (n) { if (n.template === 'CERT_REMINDER' && n.status === 'SENT') sent[n.req_id] = (sent[n.req_id] || 0) + 1; });

  state.requests.forEach(function (r) {
    if (PENDING_REQ.indexOf(r.status) === -1) return;
    var t = findType_(state, r.type_id);
    if (!t || t.doc_rule !== 'REQUIRED_IF_MIN_DAYS' && t.doc_rule !== 'REQUIRED') return;
    var needs = t.doc_rule === 'REQUIRED' || Number(r.working_days) >= Number(t.doc_min_days || 999);
    if (needs && attachmentsOf_(state, r.req_id).length === 0 && (sent[r.req_id] || 0) < maxReminders) notifyEmployee_(state, r, 'CERT_REMINDER');
  });

  var stuck = state.requests.filter(function (r) {
    var t = findType_(state, r.type_id);
    return PENDING_REQ.indexOf(r.status) !== -1 && r.start_date === state.today && t && Number(t.notice_days || 0) > 0;
  });
  stuck.forEach(function (r) {
    pushToAdmins_(['ADMIN', 'SUPER_ADMIN'], 'PENDING_TODAY', 'ใบลาเริ่มวันนี้แต่ยังไม่ได้อนุมัติ', reqRows_(state, r), r.req_id);
  });
}

/* Preview mode sample data (fictional). Add ?as=E-001 to the URL to view as the head, ?as=NEW to see first-time linking. */
(function () {
  Object.keys(SCHEMA).forEach(function (n) { __sheets[n] = [SCHEMA[n].slice()]; });
  appendObjects('LeaveTypes', SEED_LEAVE_TYPES.map(function (r) { var o = {}; SCHEMA.LeaveTypes.forEach(function (k, i) { o[k] = r[i]; }); return o; }));
  appendObjects('Settings', SEED_SETTINGS.map(function (s) { return { key: s[0], value: s[1], note: s[2] }; }));
  setSetting('company_name', 'อู่ตัวอย่าง');
  var t = todayIso();
  function nextWd(from, wd) { var d = from; while (isoWeekday(d) !== wd) d = addDays(d, 1); return d; }
  var mon = nextWd(addDays(t, 8), 1);
  appendObjects('Holidays', [{ date: addDays(mon, 14), name_th: 'วันหยุดตัวอย่าง' }]);
  appendObjects('Departments', [{ dept_id: 'D01', name: 'ช่างเคาะ 1', head_emp_id: 'E-001', max_concurrent: 1, active: true }]);
  var e = function (id, f, l, nick, hire, linked) {
    return { emp_id: id, title: 'นาย', first_name: f, last_name: l, nickname: nick, dept_id: 'D01', position: id === 'E-001' ? 'หัวหน้าช่าง' : 'ช่างเคาะ',
      hire_date: hire, birth_date: '1995-05-05', status: 'ACTIVE', line_user_id: linked ? 'U-' + id : '' };
  };
  appendObjects('Employees', [e('E-001', 'สมชาย', 'ใจดี', 'ชาย', addDays(t, -2200), true), e('E-002', 'วีระ', 'ทองดี', 'ระ', addDays(t, -800), true),
    e('E-003', 'ประยุทธ', 'ศรีสุข', 'ยุทธ', addDays(t, -1500), true), e('E-004', 'อนันต์', 'มีสุข', 'นันต์', addDays(t, -120), true)]);
  ensureGrants_();
  var now = nowStamp();
  function req(id, emp, type, s, en, status, extra) {
    var r = { req_id: id, emp_id: emp, dept_id: 'D01', type_id: type, start_date: s, end_date: en,
      working_days: workingDates(s, en, [1, 2, 3, 4, 5], {}).length, reason: 'ตัวอย่าง', status: status, approver_emp_id: emp === 'E-001' ? 'SUPER_ADMIN' : 'E-001',
      decided_by: '', decided_at: '', decision_note: '', filed_by: 'SELF', leave_year_start: '', created_at: now, updated_at: now };
    Object.keys(extra || {}).forEach(function (k) { r[k] = extra[k]; });
    var emp0 = readAll('Employees').filter(function (x) { return x.emp_id === emp; })[0];
    r.leave_year_start = leaveYearStart(emp0.hire_date, s);
    appendObjects('LeaveRequests', [r]);
    if (status === 'APPROVED') writeTakes_(loadState(), emp0, r, 'seed');
  }
  req('R-SEED1', 'E-003', 'VAC', addDays(mon, 1), addDays(mon, 2), 'APPROVED', { reason: 'กลับบ้านต่างจังหวัด' });
  req('R-SEED2', 'E-002', 'PERS', nextWd(addDays(t, 20), 3), nextWd(addDays(t, 20), 3), 'PENDING', { reason: 'พาแม่ไปหาหมอ', created_at: addDays(t, -2) + 'T09:12:00' });
  req('R-SEED3', 'E-002', 'SICK', addDays(t, -40) < t ? nextWd(addDays(t, -30), 2) : t, nextWd(addDays(t, -30), 2), 'APPROVED', { reason: 'ไข้หวัด' });
  req('R-SEED4', 'E-003', 'SICK', nextWd(addDays(t, 30), 1), addDays(nextWd(addDays(t, 30), 1), 2), 'PENDING', { reason: 'ผ่าตัดเล็ก' });
})();

window.MockApi = {
  call: function (action, data) {
    var id = __as === 'NEW' ? 'mock-NEW' : 'mock-' + __as;
    var out = JSON.parse(doPost({ postData: { contents: JSON.stringify({ action: action, idToken: id, data: data }) } }).s);
    return new Promise(function (res, rej) {
      setTimeout(function () { if (out.ok) res(out.data); else { var e = new Error(out.error.msg); e.code = out.error.code; rej(e); } }, 120);
    });
  }
};
})();
